# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3
default_install_hook_types: [commit-msg, pre-commit]
default_stages: [commit, manual]
fail_fast: true
minimum_pre_commit_version: "1.4.3"
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/ljnsn/cz-conventional-gitmoji
    rev: v0.1.2
    hooks:
      - id: conventional-gitmoji
  - repo: local
    hooks:
      - id: commitizen
        name: commitizen check
        entry: cz check
        args: [--allow-abort, --commit-msg-file]
        stages: [commit-msg]
        language: system
        require_serial: true
      - id: conventional-gitmoji
        name: gitmojify
        entry: gitmojify
        args: [--commit-msg-file]
        stages: [commit-msg]
        language: system
        require_serial: true
