site_name: Hyperfast Template
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - pymdownx.arithmatex:
      generic: true
  - admonition
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.expand
  favicon: https://assets.entelecheia.ai/favicon.png # favicon: Path to the favicon image
  logo: https://assets.entelecheia.ai/favicon.png # logo: Path to the book logo
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  analytics:
    provider: google
    property: G-SY9MF3HBFB
