---
# Warning, do not check out untrusted code with
# the pull_request_target event.
name: conventional-release-labels
on:
  workflow_dispatch:
  workflow_call:
  pull_request_target:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
