---
name: semantic-prerelease

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - pre*
      - beta*
      - alpha*
      - rc*
      - nigtly*

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    # Name the Job
    name: semantic-prerelease
    # Set the agent to run on
    runs-on: ubuntu-latest

    # Load all steps #
    steps:
      # Checkout the code base #
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # install copier and init project
      - name: Install copier and init project
        if: github.repository == 'entelecheia/hyperfast-template'
        run: |
          pipx install copier>=7.0.0
          make reinit-project-force

      # set env variable
      - name: Set env variable
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      # semantic prerelease
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          additional_options: --prerelease --verbosity=DEBUG --define=branch=${{ env.BRANCH }}
