---
name: Release

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - 'release'
      - 'beta*'
      - 'alpha*'
      - 'rc*'
    paths:
      - 'src/**'
      - 'static/**'
      - 'package.json'
      - '.copier-template/**'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Semantic release
        id: semantic_release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Release ${{github.ref}}
          title: Release ${{github.ref}}
          body: This is an automatically generated pull request created by npm run release.
          base: main
          labels: automated-pr, release
          branch: release/${{ github.sha }}
          delete-branch: true
