name: release-drafter
on:
  workflow_dispatch:
  workflow_call:

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Publish the release notes
        uses: release-drafter/release-drafter@v5.20.0
        with:
          config-name: release-drafter.yaml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
